{% set name = "sphinx-codeautolink" %}
{% set version = "0.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 93963a05f17642c8892b06932e013af62c1041a4949524c810dbc5ae8b3ff16d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
    - wheel
  run:
    - python >={{ python_min }}
    - sphinx >=3.2.0
    - beautifulsoup4 >=4.8.1
    - dataclasses
    - docutils

test:
  imports:
    - sphinx_codeautolink
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sphinx-codeautolink
  summary: Automatic links from code examples to reference documentation.
  description: |
    sphinx-codeautolink makes code examples clickable by inserting links
    from individual code elements to the corresponding reference documentation. 
    We aim for a minimal setup assuming your examples are already valid Python.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://sphinx-codeautolink.readthedocs.io/en/latest/
  dev_url: https://github.com/felix-hilden/sphinx-codeautolink

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - Zeitsperre
