{% set name = "sphinx-codeautolink" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c4f88aa4a315ee26c8c1d7ffc11b3759764fadf7d8f0a861d780d4423eff93e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - sphinx >=3.2.0
    - beautifulsoup4 >=4.8.1
    - dataclasses
    - docutils

test:
  imports:
    - sphinx_codeautolink
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sphinx-codeautolink
  summary: Automatic links from code examples to reference documentation.
  description: |
    sphinx-codeautolink makes code examples clickable by inserting links
    from individual code elements to the corresponding reference documentation. 
    We aim for a minimal setup assuming your examples are already valid Python.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://sphinx-codeautolink.readthedocs.io/en/latest/
  dev_url: https://github.com/felix-hilden/sphinx-codeautolink

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - Zeitsperre
